### ISSUE TITLE
jellyfin - values.schema.json is to aggressive

### ISSUE THREAD

**Issue by Brice187** [loeken/helm-charts#293]
The introduction of schemes:  https://github.com/loeken/helm-charts/commit/4fd660e150b8435f03b7bcc2480e52e6e646a5a2 broke my jellyfin:

```
Error: Error: values don't meet the specifications of the schema(s) in the following chart(s): jellyfin: - ingress.main: Additional property ingressClassName is not allowed - ingress.main: Must validate all the schemas (allOf) - persistence.cache: Must validate one and only one schema (oneOf) - persistence.cache: accessMode is required - persistence.cache: size is required - persistence.cache: Additional property mountPath is not allowed - persistence.cache: Must validate all the schemas (allOf)
```

corresponding values:
```yaml
ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    ingressClassName: "cilium"
    labels: {}
    hosts:
      - host: "jellyfin.k3s.home"
        paths:
          - path: /
            service:
              name: jellyfin
              port: 8096

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 8Gi

  # Cache does NOT contain temporary transcoding data.
  cache:
    enabled: false
    mountPath: /cache

  media:
    enabled: true
    type: nfs
    server: 192.168.7.26
    path: /Multimedia
```
My workaround is to stick to chart version 10.10.6 and set image to 10.10.7
